import fs from 'fs';

// Smart Vietnamese de-spacing for EduQuiz PDF print artifacts
function fixEduQuizSpacing(text) {
  if (!text) return '';
  let s = text.normalize('NFC');
  
  // Specific words frequently broken by EduQuiz PDF font rendering:
  const wordMap = [
    [/đ\s*ư\s*ợ\s*c/gi, 'được'],
    [/đ\s*ư\s*a/gi, 'đưa'],
    [/đ\s*ầ\s*u/gi, 'đầu'],
    [/đ\s*á\s*p\s*á\s*n/gi, 'đáp án'],
    [/đ\s*ú\s*n\s*g/gi, 'đúng'],
    [/đ\s*â\s*y/gi, 'đây'],
    [/đ\s*ó/gi, 'đó'],
    [/đ\s*i/gi, 'đi'],
    [/đ\s*ồ\s*n\s*g/gi, 'đồng'],
    [/đ\s*ị\s*n\s*h/gi, 'định'],
    [/đ\s*ặ\s*t/gi, 'đặt'],
    [/đ\s*ơ\s*n/gi, 'đơn'],
    [/đ\s*ộ\s*c/gi, 'độc'],
    [/đ\s*ạ\s*i/gi, 'đại'],
    [/đ\s*i\s*ể\s*m/gi, 'điểm'],
    [/đ\s*o\s*ạ\s*n/gi, 'đoạn'],
    [/đ\s*o\s*à\s*n/gi, 'đoàn'],
    [/đ\s*ố\s*i/gi, 'đối'],
    [/đ\s*ó\s*n\s*g/gi, 'đóng'],
    [/đ\s*ộ\s*n\s*g/gi, 'động'],
    [/đ\s*ư\s*ờ\s*n\s*g/gi, 'đường'],
    [/m\s*ã/gi, 'mã'],
    [/n\s*g\s*u\s*ồ\s*n/gi, 'nguồn'],
    [/m\s*ở/gi, 'mở'],
    [/p\s*h\s*ầ\s*n/gi, 'phần'],
    [/t\s*ạ\s*o/gi, 'tạo'],
    [/m\s*ô\s*i/gi, 'môi'],
    [/t\s*r\s*ư\s*ờ\s*n\s*g/gi, 'trường'],
    [/b\s*ạ\s*n/gi, 'bạn'],
    [/c\s*h\s*ọ\s*n/gi, 'chọn'],
    [/n\s*h\s*ì\s*n/gi, 'nhìn'],
    [/v\s*à\s*o/gi, 'vào'],
    [/h\s*ì\s*n\s*h/gi, 'hình'],
    [/k\s*h\s*ô\s*n\s*g/gi, 'không'],
    [/t\s*h\s*ư\s*v\s*i\s*ệ\s*n/gi, 'thư viện'],
    [/c\s*h\s*ứ\s*c/gi, 'chức'],
    [/n\s*ă\s*n\s*g/gi, 'năng'],
    [/t\s*ư\s*ơ\s*n\s*g/gi, 'tương'],
    [/đ\s*ư\s*ơ\s*n\s*g/gi, 'đương'],
    [/v\s*ớ\s*i/gi, 'với'],
    [/q\s*u\s*a\s*n/gi, 'quan'],
    [/n\s*i\s*ệ\s*m/gi, 'niệm'],
    [/n\s*à\s*o/gi, 'nào'],
    [/s\s*a\s*u/gi, 'sau'],
    [/s\s*a\s*i/gi, 'sai'],
    [/k\s*ý/gi, 'ký'],
    [/h\s*i\s*ệ\s*u/gi, 'hiệu'],
    [/c\s*ủ\s*a/gi, 'của'],
    [/v\s*ò\s*n\s*g/gi, 'vòng'],
    [/t\s*r\s*ò\s*n/gi, 'tròn'],
    [/v\s*u\s*ô\s*n\s*g/gi, 'vuông'],
    [/c\s*h\s*ữ/gi, 'chữ'],
    [/n\s*g\s*ư\s*ợ\s*c/gi, 'ngược'],
    [/t\s*r\s*o\s*n\s*g/gi, 'trong'],
    [/b\s*ằ\s*n\s*g/gi, 'bằng'],
    [/s\s*ố/gi, 'số'],
    [/p\s*h\s*â\s*n/gi, 'phân'],
    [/m\s*ề\s*m/gi, 'mềm'],
    [/t\s*h\s*i\s*ế\s*t/gi, 'thiết'],
    [/l\s*ậ\s*p/gi, 'lập'],
    [/k\s*h\s*ó\s*a/gi, 'khóa'],
    [/h\s*ọ\s*c/gi, 'học'],
    [/t\s*h\s*ô\s*n\s*g/gi, 'thông'],
    [/t\s*i\s*n/gi, 'tin'],
    [/c\s*á/gi, 'cá'],
    [/n\s*h\s*â\s*n/gi, 'nhân'],
    [/t\s*à\s*i/gi, 'tài'],
    [/k\s*h\s*o\s*ả\s*n/gi, 'khoản'],
    [/t\s*h\s*ê\s*m/gi, 'thêm'],
    [/s\s*ử\s*a/gi, 'sửa'],
    [/x\s*ó\s*a/gi, 'xóa'],
    [/b\s*á\s*o/gi, 'báo'],
    [/c\s*á\s*o/gi, 'cáo'],
    [/h\s*o\s*ạ\s*t/gi, 'hoạt'],
    [/đ\s*ộ\s*n\s*g/gi, 'động'],
    [/d\s*u\s*n\s*g/gi, 'dung'],
    [/l\s*ư\s*ợ\s*n\s*g/gi, 'lượng'],
    [/h\s*ệ/gi, 'hệ'],
    [/t\s*h\s*ố\s*n\s*g/gi, 'thống'],
    [/t\s*r\s*a\s*n\s*g/gi, 'trang'],
    [/k\s*h\s*ố\s*i/gi, 'khối'],
    [/m\s*ú\s*i/gi, 'múi'],
    [/g\s*i\s*ờ/gi, 'giờ'],
    [/n\s*g\s*ô\s*n/gi, 'ngôn'],
    [/n\s*g\s*ữ/gi, 'ngữ'],
    [/c\s*h\s*í\s*n\s*h/gi, 'chính'],
    [/s\s*á\s*c\s*h/gi, 'sách'],
    [/b\s*ả\s*o/gi, 'bảo'],
    [/m\s*ậ\s*t/gi, 'mật'],
    [/t\s*r\s*ì\s*n\s*h/gi, 'trình'],
    [/b\s*à\s*y/gi, 'bày'],
    [/t\s*h\s*ư/gi, 'thư'],
    [/đ\s*i\s*ệ\s*n/gi, 'điện'],
    [/t\s*ử/gi, 'tử'],
    [/q\s*u\s*ả\s*n/gi, 'quản'],
    [/l\s*ý/gi, 'lý'],
    [/p\s*h\s*i\s*ê\s*n/gi, 'phiên'],
    [/l\s*à\s*m/gi, 'làm'],
    [/v\s*i\s*ệ\s*c/gi, 'việc'],
    [/n\s*h\s*ậ\s*t/gi, 'nhật'],
    [/k\s*ý/gi, 'ký'],
    [/l\s*ư\s*u/gi, 'lưu'],
    [/t\s*h\s*ố\s*n\s*g/gi, 'thống'],
    [/k\s*ê/gi, 'kê'],
    [/c\s*h\s*ủ/gi, 'chủ'],
    [/đ\s*ề/gi, 'đề'],
    [/m\s*ụ\s*c/gi, 'mục'],
    [/b\s*à\s*i/gi, 'bài'],
    [/g\s*i\s*ả\s*n\s*g/gi, 'giảng'],
    [/c\s*h\s*u\s*ẩ\s*n/gi, 'chuẩn'],
    [/t\s*ó\s*m/gi, 'tóm'],
    [/t\s*ắ\s*t/gi, 'tắt'],
    [/n\s*g\s*à\s*y/gi, 'ngày'],
    [/b\s*ắ\s*t/gi, 'bắt'],
    [/c\s*ơ/gi, 'cơ'],
    [/s\s*ở/gi, 'sở'],
    [/d\s*ữ/gi, 'dữ'],
    [/l\s*i\s*ệ\s*u/gi, 'liệu'],
    [/k\s*h\s*ô\s*i/gi, 'khôi'],
    [/p\s*h\s*ụ\s*c/gi, 'phục'],
    [/t\s*r\s*u\s*y/gi, 'truy'],
    [/v\s*ấ\s*n/gi, 'vấn'],
    [/k\s*i\s*ể\s*m/gi, 'kiểm'],
    [/t\s*r\s*a/gi, 'tra'],
    [/b\s*a\s*o/gi, 'bao'],
    [/n\s*h\s*i\s*ê\s*u/gi, 'nhiêu'],
    [/t\s*h\s*a\s*o/gi, 'thao'],
    [/t\s*á\s*c/gi, 'tác'],
    [/g\s*ó\s*i/gi, 'gói'],
    [/q\s*u\s*y/gi, 'quy'],
    [/t\s*ắ\s*c/gi, 'tắc'],
    [/đ\s*ò\s*i/gi, 'đòi'],
    [/h\s*ỏ\s*i/gi, 'hỏi'],
    [/a\s*i/gi, 'ai'],
    [/l\s*à/gi, 'là'],
    [/n\s*g\s*ư\s*ờ\s*i/gi, 'người'],
    [/p\s*h\s*ả\s*i/gi, 'phải'],
    [/t\s*u\s*â\s*n/gi, 'tuân'],
    [/t\s*h\s*e\s*o/gi, 'theo'],
    [/t\s*ổ/gi, 'tổ'],
    [/c\s*h\s*ứ\s*c/gi, 'chức'],
    [/n\s*h\s*ư/gi, 'như'],
    [/t\s*h\s*ế/gi, 'thế'],
    [/c\s*ộ\s*n\s*g/gi, 'cộng'],
    [/đ\s*ồ\s*n\s*g/gi, 'đồng'],
    [/t\s*h\s*u\s*ậ\s*n/gi, 'thuận'],
    [/d\s*ự/gi, 'dự'],
    [/á\s*n/gi, 'án'],
    [/v\s*a\s*i/gi, 'vai'],
    [/t\s*r\s*ò/gi, 'trò'],
    [/m\s*ô/gi, 'mô'],
    [/đ\s*i\s*ề\s*u/gi, 'điều'],
    [/h\s*à\s*n\s*h/gi, 'hành'],
    [/n\s*h\s*â\s*n/gi, 'nhân'],
    [/t\s*ừ/gi, 'từ'],
    [/c\s*h\s*ế/gi, 'chế'],
    [/t\s*à\s*i/gi, 'tài'],
    [/l\s*ã\s*n\s*h/gi, 'lãnh'],
    [/đ\s*ạ\s*o/gi, 'đạo'],
    [/c\s*ô\s*n\s*g/gi, 'công'],
    [/c\s*ụ/gi, 'cụ'],
    [/c\s*ố\s*t/gi, 'cốt'],
    [/l\s*õ\s*i/gi, 'lõi'],
    [/t\s*ấ\s*t/gi, 'tất'],
    [/c\s*ả/gi, 'cả'],
    [/n\s*ê\s*n/gi, 'nên'],
    [/p\s*h\s*á\s*t/gi, 'phát'],
    [/b\s*i\s*ể\s*u/gi, 'biểu'],
    [/c\s*ó/gi, 'có'],
    [/t\s*h\s*ể/gi, 'thể'],
    [/t\s*ả\s*i/gi, 'tải'],
    [/v\s*ề/gi, 'về'],
    [/t\s*à\s*i/gi, 'tài'],
    [/l\s*i\s*ệ\s*u/gi, 'liệu'],
    [/đ\s*ó\s*n\s*g/gi, 'đóng'],
    [/g\s*ó\s*p/gi, 'góp']
  ];

  for (const [regex, rep] of wordMap) {
    s = s.replace(regex, rep);
  }

  // Regex pass: single letters separated by space
  s = s.replace(/([a-zA-ZàáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđĐ])\s+([àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵ])/g, '$1$2');
  s = s.replace(/([ươâăêô])\s+([a-zA-ZàáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđĐ])/g, '$1$2');
  s = s.replace(/\s+/g, ' ').trim();
  return s;
}

console.log('Test spacing fix:');
console.log(fixEduQuizSpacing('Nhìn vào hình 02, để t ạ o m ô i tr ư ờ ng Web và CSDL b ạ n ch ọ n?'));
console.log(fixEduQuizSpacing('Quan ni ệ m nào sau đ ây sai v ề Copyleft:'));
console.log(fixEduQuizSpacing('A. Đư ợ c đư a ra d ự a trên Copyright'));
